export const genreOptions = [
  { value: "literary fiction", label: "Literary Fiction" },
  { value: "mystery", label: "Mystery" },
  { value: "crime", label: "Crime" },
  { value: "fantasy", label: "Fantasy" },
  { value: "science fiction", label: "Science Fiction" },
  { value: "historical fiction", label: "Historical Fiction" },
  { value: "horror", label: "Horror" },
  { value: "thriller", label: "Thriller" },
  { value: "suspense", label: "Suspense" },
  { value: "magical realism", label: "Magical Realism" },
  { value: "adventure", label: "Adventure" },
  { value: "biography", label: "Biography" },
  { value: "autobiography", label: "Autobiography" },
  { value: "memoir", label: "Memoir" },
  { value: "self-help", label: "Self-Help" },
  { value: "personal development", label: "Personal Development" },
  { value: "history", label: "History" },
  { value: "science and technology", label: "Science and Technology" },
  { value: "philosophy", label: "Philosophy" },
  { value: "religion", label: "Religion" },
  { value: "spirituality", label: "Spirituality" },
  { value: "travel", label: "Travel" },
  { value: "true crime", label: "True Crime" },
];

export const subgenreOptions = [
  { value: "chick-lit", label: "Chick-Lit" },
  { value: "christian", label: "Christian" },
  { value: "contemporary", label: "Contemporary" },
  { value: "erotica", label: "Erotica" },
  { value: "glitz/glamor", label: "Glitz/Glamor" },
  { value: "historical", label: "Historical" },
  { value: "multicultural", label: "Multicultural" },
  { value: "paranormal", label: "Paranormal" },
  { value: "romantic comedy", label: "Romantic Comedy" },
  { value: "romantic suspense", label: "Romantic Suspense" },
  { value: "sensual", label: "Sensual" },
  { value: "spicy", label: "Spicy" },
  { value: "sweet", label: "Sweet" },
  { value: "young adult", label: "Young Adult" },
  { value: "child in peril", label: "Child in Peril" },
  { value: "comic horror", label: "Comic Horror" },
  { value: "creepy kids", label: "Creepy Kids" },
  { value: "dark fantasy", label: "Dark Fantasy" },
  { value: "dark mystery/noir", label: "Dark Mystery/Noir" },
  { value: "erotic vampire", label: "Erotic Vampire" },
  { value: "fabulist", label: "Fabulist" },
  { value: "gothic", label: "Gothic" },
  { value: "hauntings", label: "Hauntings" },
  { value: "historical horror", label: "Historical Horror" },
  { value: "monster horror", label: "Monster Horror" },
  { value: "psychological horror", label: "Psychological Horror" },
  { value: "slasher", label: "Slasher" },
  { value: "splatterpunk", label: "Splatterpunk" },
  { value: "supernatural horror", label: "Supernatural Horror" },
  { value: "vampire", label: "Vampire" },
  { value: "werewolf", label: "Werewolf" },
  { value: "zombie", label: "Zombie" },
  { value: "action/adventure", label: "Action/Adventure" },
  { value: "conspiracy", label: "Conspiracy" },
  { value: "courtroom drama", label: "Courtroom Drama" },
  { value: "espionage", label: "Espionage" },
  { value: "forensic", label: "Forensic" },
  { value: "hard-boiled", label: "Hard-Boiled" },
  { value: "historical mystery", label: "Historical Mystery" },
  { value: "legal thriller", label: "Legal Thriller" },
  { value: "medical thriller", label: "Medical Thriller" },
  { value: "noir", label: "Noir" },
  { value: "police procedural", label: "Police Procedural" },
  { value: "political thriller", label: "Political Thriller" },
  { value: "psychological thriller", label: "Psychological Thriller" },
  { value: "spy", label: "Spy" },
  { value: "supernatural thriller", label: "Supernatural Thriller" },
  { value: "techno-thriller", label: "Techno-Thriller" },
  { value: "whodunit", label: "Whodunit" },
  { value: "alternate history", label: "Alternate History" },
  { value: "apocalyptic", label: "Apocalyptic" },
  { value: "cyberpunk", label: "Cyberpunk" },
  { value: "dystopian", label: "Dystopian" },
  { value: "hard science fiction", label: "Hard Science Fiction" },
  { value: "military science fiction", label: "Military Science Fiction" },
  { value: "parallel universe", label: "Parallel Universe" },
  { value: "post-apocalyptic", label: "Post-Apocalyptic" },
  { value: "soft science fiction", label: "Soft Science Fiction" },
  { value: "space opera", label: "Space Opera" },
  { value: "steampunk", label: "Steampunk" },
  { value: "time travel", label: "Time Travel" },
  { value: "urban fantasy", label: "Urban Fantasy" },
  { value: "epic fantasy", label: "Epic Fantasy" },
  { value: "high fantasy", label: "High Fantasy" },
  { value: "historical fantasy", label: "Historical Fantasy" },
  { value: "low fantasy", label: "Low Fantasy" },
  { value: "magic realism", label: "Magic Realism" },
  { value: "mythic", label: "Mythic" },
  { value: "sword and sorcery", label: "Sword and Sorcery" },
  { value: "fairy tale", label: "Fairy Tale" },
  { value: "fables", label: "Fables" },
  { value: "folklore", label: "Folklore" },
  { value: "legend", label: "Legend" },
  { value: "myth", label: "Myth" },
  { value: "parable", label: "Parable" },
  { value: "tall tale", label: "Tall Tale" },
  { value: "coming-of-age", label: "Coming-of-Age" },
  { value: "bildungsroman", label: "Bildungsroman" },
  { value: "campus novel", label: "Campus Novel" },
  { value: "family saga", label: "Family Saga" },
  { value: "picaresque", label: "Picaresque" },
  { value: "satire", label: "Satire" },
  { value: "social commentary", label: "Social Commentary" },
  { value: "women's fiction", label: "Women's Fiction" },
  { value: "lad lit", label: "Lad Lit" },
  { value: "new adult", label: "New Adult" },
  { value: "upmarket fiction", label: "Upmarket Fiction" },
  { value: "literary fiction", label: "Literary Fiction" },
  { value: "experimental", label: "Experimental" },
  { value: "metafiction", label: "Metafiction" },
  { value: "slipstream", label: "Slipstream" },
  { value: "bizarro", label: "Bizarro" },
  { value: "transgressive", label: "Transgressive" },
  { value: "gothic romance", label: "Gothic Romance" },
  { value: "inspirational", label: "Inspirational" },
  { value: "medical romance", label: "Medical Romance" },
  { value: "paranormal romance", label: "Paranormal Romance" },
  { value: "regency romance", label: "Regency Romance" },
  { value: "science fiction romance", label: "Science Fiction Romance" },
  { value: "western romance", label: "Western Romance" },
  { value: "chick lit", label: "Chick Lit" },
  { value: "domestic fiction", label: "Domestic Fiction" },
  { value: "family drama", label: "Family Drama" },
  { value: "legal drama", label: "Legal Drama" },
  { value: "medical drama", label: "Medical Drama" },
  { value: "political fiction", label: "Political Fiction" },
  { value: "psychological fiction", label: "Psychological Fiction" },
  { value: "religious fiction", label: "Religious Fiction" },
  { value: "saga", label: "Saga" },
  { value: "sports fiction", label: "Sports Fiction" },
  { value: "war fiction", label: "War Fiction" },
  { value: "detective", label: "Detective" },
  { value: "legal", label: "Legal" },
  { value: "medical", label: "Medical" },
  { value: "psychological", label: "Psychological" },
];

export const specialAudienceOptions = [
  "middle grade",
  "young adult",
  "graphic novel/comic book",
  "children/picture book",
  "none",
];

export const QUERY_LIMIT = 21;
