import type { Metadata } from 'next';
import { Fragment } from 'react';
import Link from 'next/link';
import Image from 'next/image';

const PAGE_DATA = {
  "slug": "how-to-write-an-author-bio-that-makes-a-literary-agent-keep-reading",
  "title": "How to write an author bio that makes a literary agent keep reading",
  "description": "A lot of writers treat the author bio like a formality: \"Here's my name. Here are my accomplishments. Anyway, here's the book.\"",
  "readTime": "13 min read",
  "publishedDate": null,
  "modifiedDate": null,
  "canonicalUrl": "https://writequeryhook.com/blog/how-to-write-an-author-bio-that-makes-a-literary-agent-keep-reading",
  "siteUrl": "https://writequeryhook.com",
  "siteName": "Write Query Hook",
  "locale": "en-US",
  "articleSection": "Querying",
  "keywords": [
    "author bios",
    "submissions",
    "craft",
    "agents",
    "agent attention",
    "quick snapshot",
    "honesty",
    "specifics",
    "awkward self-promotion",
    "voice signal",
    "sneak peek",
    "match"
  ],
  "author": null,
  "hero": {
    "url": "https://ik.imagekit.io/8cxvcsdnz/wqh/sprint_06/day_079/how-to-write-an-author-bio-that-makes-a-literary-agent-keep-reading/blog/blog_hero_query_anxiety_tiny_bio_blog_hero_landscape_653a672f0f3e.jpeg?updatedAt=1782427090361",
    "alt": "blog hero \u00b7 query anxiety tiny bio",
    "width": 3736,
    "height": 2393,
    "creator": "Aykut \u00d6zen",
    "creatorUrl": "https://www.pexels.com/@aykut-ozen-2159946844",
    "provider": "pexels",
    "role": "hero"
  },
  "breadcrumbs": [
    {
      "name": "Home",
      "item": "/"
    },
    {
      "name": "Blog",
      "item": "/blog"
    },
    {
      "name": "How to write an author bio that makes a literary agent keep reading",
      "item": "https://writequeryhook.com/blog/how-to-write-an-author-bio-that-makes-a-literary-agent-keep-reading"
    }
  ],
  "tldrBlocks": [],
  "openingBlocks": [
    {
      "type": "paragraph",
      "text": "A lot of writers treat the **author bio** like a formality: \"Here's my name. Here are my accomplishments. Anyway, here's the book.\""
    },
    {
      "type": "paragraph",
      "text": "That's how you end up with a bio that reads like it was generated by a template you never agreed to. And yes, it feels weird\u2014because a bio is **self-promotion** with a word limit and a judge who can't be bothered to guess who you are."
    },
    {
      "type": "paragraph",
      "text": "So here's the case-study lens: not \"what is a bio,\" but **what your bio does** inside a real query package\u2014before pages even matter, before an agent understands your **writing voice** from prose."
    },
    {
      "type": "blockquote",
      "text": "\"Your bio is the first taste of who you are\u2014and agents notice.\""
    },
    {
      "type": "paragraph",
      "text": "Here are three example bios (constructed to mirror common patterns). Then we'll pull the craft moves you can steal for your **query letter** so the whole submission reads like one person, not a group project."
    }
  ],
  "sections": [
    {
      "section_id": "h2_tldr",
      "heading": "TLDR",
      "heading_slug": "tldr",
      "keyword_key": "h2_tldr",
      "keywords": [],
      "blocks": [
        {
          "type": "list",
          "items": [
            "Your **author bio** is a first-impression tool: it signals voice and expectations fast.",
            "Choose distinctive specifics over accomplishments-by-default.",
            "Humor can work, but only when it's grounded in real perspective and not \"look at me\" energy.",
            "Tight **query letter** and bio pairing matters: both should point to the same book-version of you.",
            "Connect your bio to your writing by naming themes, beliefs, or lived observations\u2014not just genres.",
            "Treat your bio as a sneak peek into the person behind the book, not a performance."
          ]
        }
      ],
      "image": null
    },
    {
      "section_id": "h2_opening_why_bios_are_sneak_peeks_not_r_sum_blurbs",
      "heading": "Opening \u2014 why bios are sneak peeks, not r\u00e9sum\u00e9 blurbs",
      "heading_slug": "opening-why-bios-are-sneak-peeks-not-resume-blurbs",
      "keyword_key": "h2_opening_why_bios_are_sneak_peeks_not_r_sum_blurbs",
      "keywords": [],
      "blocks": [
        {
          "type": "paragraph",
          "text": "When an agent reads, they're scanning for match: does your book sound like your book on the page, and does your bio sound like the *same* human who wrote it?"
        },
        {
          "type": "paragraph",
          "text": "That's why bios matter in a query. They're not \"extra.\" They're the first taste of **writing voice**, and they help a **literary agent** decide whether your work is likely to land with their taste (and their list). Even if they don't love your query letter on first read, a sharp bio can buy attention. Not because it's clever. Because it's clear."
        },
        {
          "type": "paragraph",
          "text": "Most writers struggle with what to include beyond basic facts. They worry the bio won't stand out. They also feel awkward \"selling themselves,\" especially when the instruction says to show personality in a short space. And then there's the third problem: connecting real-life experiences and writing themes into something an agent can understand instantly."
        },
        {
          "type": "paragraph",
          "text": "This case-study is built to solve those exact issues\u2014by showing what changes when you stop writing \"about me\" and start writing **for the match**."
        },
        {
          "type": "blockquote",
          "text": "\"Treat your bio like a sneak peek into the person behind the book.\""
        }
      ],
      "image": {
        "url": "https://ik.imagekit.io/8cxvcsdnz/wqh/sprint_06/day_079/how-to-write-an-author-bio-that-makes-a-literary-agent-keep-reading/blog/blog_section_image_opening_why_bios_are_sneak_peeks_not_resume_blur_blog_section_landscape_b2ff32c66109.gif?updatedAt=1782427091018",
        "alt": "Opening \u2014 why bios are sneak peeks, not r\u00e9sum\u00e9 blurbs",
        "width": 279,
        "height": 200,
        "creator": "Giphy",
        "creatorUrl": "https://giphy.com/gifs/fight-club-edward-norton-writing-Y5ytdl4PXziZW",
        "provider": "giphy",
        "role": "section"
      }
    },
    {
      "section_id": "h2_breakdown_example_1_specifics_over_compliments",
      "heading": "Body \u2014 structural breakdown",
      "heading_slug": "body-structural-breakdown",
      "keyword_key": "h2_breakdown_example_1_specifics_over_compliments",
      "keywords": [
        "distinct details",
        "lived experience",
        "specificity",
        "boring accomplishments",
        "delete button",
        "pencil edits",
        "eye roll at generic",
        "concrete nouns",
        "memorable",
        "rewrite"
      ],
      "blocks": [
        {
          "type": "subheading",
          "text": "How an author bio functions as the first impression in a query"
        },
        {
          "type": "paragraph",
          "text": "Before we touch examples, pause on the mechanics: a query is already a constrained document. The **query letter** carries your hook and positioning. The synopsis (if you're including it) carries the story spine. The pages carry craft."
        },
        {
          "type": "paragraph",
          "text": "So what should your bio carry instead?"
        },
        {
          "type": "paragraph",
          "text": "Your full life doesn't belong there. Every credential doesn't belong there. A checklist of accomplishments you can verify doesn't belong there either."
        },
        {
          "type": "paragraph",
          "text": "Your bio should carry **voice signals**: the distinctive way you see the world and the kind of attention you bring to a page."
        },
        {
          "type": "paragraph",
          "text": "A bio that works tends to do three things, quickly:"
        },
        {
          "type": "paragraph",
          "text": "1. **It names a \"person-shaped\" perspective.** Not \"I love books,\" but what your attention tends to land on. 2. **It points at storytelling expectations.** If your novel is funny-but-devastating, your bio should have the same tonal logic. 3. **It gives a few concrete anchors** (what you do, what you've lived, what you believe) that an agent can connect to the manuscript."
        },
        {
          "type": "paragraph",
          "text": "The mistake writers make is treating the bio like a mini r\u00e9sum\u00e9. R\u00e9sum\u00e9s are designed to prove competence. Bios in a **query letter** context are designed to prove *fit*."
        },
        {
          "type": "blockquote",
          "text": "In a query, your bio reduces uncertainty about what kind of writer you are, not your ability to impress."
        },
        {
          "type": "paragraph",
          "text": "That's also why this matters to **literary agent** reading. They're not just evaluating your plot; they're evaluating your consistency: can they imagine you writing the kind of scenes your genre promises?"
        },
        {
          "type": "paragraph",
          "text": "If your bio is generic, the agent has no extra signal to use. If your bio is specific, they gain a \"reading shortcut.\" It's the same job as craft, just in one paragraph."
        },
        {
          "type": "paragraph",
          "text": "#### Generalizable lesson Write your bio like it's answering three questions an agent is already trying to resolve:"
        },
        {
          "type": "list",
          "items": [
            "What kind of human wrote this?",
            "What tone and preoccupations does this person bring?",
            "What should I expect on the page?"
          ]
        },
        {
          "type": "subheading",
          "text": "Breakdown example 1 \u2014 specifics over compliments (the \"delete my r\u00e9sum\u00e9\" rewrite)"
        },
        {
          "type": "paragraph",
          "text": "Here's a common **author bio** pattern. Notice how it can be technically true and still fail."
        },
        {
          "type": "paragraph",
          "text": "**Example A (generic, r\u00e9sum\u00e9-ish):** \"I write contemporary fiction. My work has been published in literary magazines. I'm passionate about storytelling and character development. I live in New York.\""
        },
        {
          "type": "paragraph",
          "text": "This bio doesn't do anything wrong, exactly. It's just empty where an agent needs signal. \"Contemporary fiction\" tells almost nothing. \"Published in literary magazines\" is vague. \"Passionate\" is a personality substitute. \"Character development\" is an industry phrase that doesn't distinguish you from every other writer on PubTips."
        },
        {
          "type": "paragraph",
          "text": "It also doesn't answer the pain point writers have: \"What do I include beyond basic facts?\" This tries to be safe. Safe is forgettable."
        },
        {
          "type": "paragraph",
          "text": "Now compare it to a rewritten version built around concrete anchors (still intermediate-friendly; still query-stage appropriate)."
        },
        {
          "type": "paragraph",
          "text": "**Example A (specific, voice-signaling):** \"I write stories about people who can't stop noticing the small humiliations life hands them. By day, I work in [real job field], which means I spend my days listening to how people explain themselves when they're stressed. My fiction keeps returning to that moment\u2014when a person tries to be 'fine' and fails.\""
        },
        {
          "type": "paragraph",
          "text": "The difference isn't \"better writing\" in the abstract. It's that the second bio gives the agent something to hold in their head. They can picture the scenes your **writing voice** likely produces: the attention to micro-behavior, the interest in stressed self-narration, the recurring tonal logic."
        },
        {
          "type": "paragraph",
          "text": "Also: it doesn't over-claim. It doesn't say \"I'm the best\" (because that's cringe in 120 words). It shows the kind of attention you bring."
        },
        {
          "type": "blockquote",
          "text": "\"Authenticity beats polish: show personality, then let your themes come through.\""
        },
        {
          "type": "paragraph",
          "text": "#### Generalizable lesson Use specifics that do at least one of these jobs:"
        },
        {
          "type": "list",
          "items": [
            "Show what you notice (your lens).",
            "Show what you've lived through (even indirectly).",
            "Show what you care about when nobody's applauding (belief, preoccupation, conflict type)."
          ]
        },
        {
          "type": "paragraph",
          "text": "If your bio can be swapped into a hundred other writer submissions and still read okay, it's too generic. Cut until it only fits you."
        },
        {
          "type": "subheading",
          "text": "Breakdown example 2 \u2014 humor and authenticity without cringe self-worship"
        },
        {
          "type": "paragraph",
          "text": "Now let's tackle the self-promotion fear. Many writers think a funny bio must sound like a performance. Then they either go silent (\"I don't know what to say\") or they oversell (\"I'm hilarious!\")."
        },
        {
          "type": "paragraph",
          "text": "**Example B (awkward self-promo):** \"I'm a funny writer with a sharp voice and lots of charisma. I've always loved comedy. My friends say I should write a blog. This book will make you laugh.\""
        },
        {
          "type": "paragraph",
          "text": "This one has two problems: 1. It talks at the reader (\"make you laugh\") instead of showing how the writer thinks. 2. It relies on claims that can't be verified in a short bio (\"charisma,\" \"sharp voice\")\u2014and agents hate betting on unsupported vibes."
        },
        {
          "type": "paragraph",
          "text": "Here's a version that keeps humor, but earns it by tying it to perspective and story expectations."
        },
        {
          "type": "paragraph",
          "text": "**Example B (humor grounded in lived perspective):** \"I've spent years watching people perform competence right up until the moment something breaks. I write comedy that keeps one hand on the laugh and one hand on the bruise\u2014because that's the only way I know to tell the truth. If my characters sound 'fine,' it won't last.\""
        },
        {
          "type": "paragraph",
          "text": "This is still a case-study example, but the craft principle is real: humor in a bio works when it's less \"I'm funny\" and more \"this is the angle I use to see the world.\""
        },
        {
          "type": "paragraph",
          "text": "Also, the tone matches what an agent needs: it doesn't demand agreement; it invites recognition. And that's what authenticity feels like in a short bio: clarity about how you see and what you believe."
        },
        {
          "type": "paragraph",
          "text": "This is where the pain point lands: many feel awkward **selling themselves**. The fix is to stop selling yourself like a product and start presenting your **writing voice** as an already-existing worldview."
        },
        {
          "type": "paragraph",
          "text": "#### Generalizable lesson To make humor believable in an **author bio**, use a pattern like:"
        },
        {
          "type": "list",
          "items": [
            "claim-free tone signal (\"I write X kind of truth\")",
            "concrete attention (\"people perform competence\")",
            "a tonal promise tied to conflict (\"if they sound fine, it won't last\")"
          ]
        },
        {
          "type": "paragraph",
          "text": "Your bio should hint at the kind of scenes an agent will later experience in your pages."
        },
        {
          "type": "subheading",
          "text": "Breakdown example 3 \u2014 matching your bio to your work (themes as fingerprints)"
        },
        {
          "type": "paragraph",
          "text": "This is the hardest part for writers: connecting real experiences and themes into something an agent understands instantly."
        },
        {
          "type": "paragraph",
          "text": "A lot of people try to \"match\" by listing topics. \"I write about grief, family, and resilience.\" That can be true and still not match."
        },
        {
          "type": "paragraph",
          "text": "Why? Because it's theme soup. It doesn't show the *specific* way you treat those themes\u2014the tonal stance, the kind of character decisions you make, the conflict engine you prefer."
        },
        {
          "type": "paragraph",
          "text": "So instead of \"themes,\" think **fingerprints**."
        },
        {
          "type": "paragraph",
          "text": "**Example C (theme list, mismatch risk):** \"I write about love, loss, and redemption. My work explores family relationships and the power of hope.\""
        },
        {
          "type": "paragraph",
          "text": "**Example C (theme fingerprints, manuscript-ready match):** \"My stories borrow their structure from arguments that never end: the sentences where someone insists they're okay, then quietly proves they aren't. I'm drawn to characters who keep translating other people's moods into something they can survive. If there's hope in my books, it's earned the hard way.\""
        },
        {
          "type": "paragraph",
          "text": "Now you can \"see\" the work. The agent can connect the bio to the kind of emotional rhythm the manuscript likely follows: argument-driven scenes, self-justifying characters, translating others' moods, hard-earned hope."
        },
        {
          "type": "paragraph",
          "text": "**How to match your bio to your writing** is straightforward: describe the *mechanism* of your storytelling\u2014what kinds of moments you return to, how you turn lived observation into scenes, what belief you interrogate\u2014instead of listing topics."
        },
        {
          "type": "paragraph",
          "text": "And yes\u2014this is also **how to write an author bio for queries** that actually helps. The bio is the micro-signal of your manuscript's tone, not the r\u00e9sum\u00e9 addendum."
        },
        {
          "type": "blockquote",
          "text": "\"Standout bios include distinctive, specific details that connect to your themes or storytelling style.\""
        },
        {
          "type": "paragraph",
          "text": "#### Generalizable lesson Make your bio match your manuscript by including one \"fingerprint\" sentence:"
        },
        {
          "type": "list",
          "items": [
            "the kind of moment you write",
            "the kind of character who populates that moment",
            "the tonal stance you take toward it"
          ]
        },
        {
          "type": "paragraph",
          "text": "Everything else should support that, not replace it."
        },
        {
          "type": "subheading",
          "text": "How to use your bio as a partner to your query letter"
        },
        {
          "type": "paragraph",
          "text": "Here's the final assembly problem: a lot of writers write the bio first, then write the query letter like it's a separate document with different DNA. That causes friction. The agent reads the query and thinks \"I don't quite believe this person wrote the book,\" or reads the bio and thinks \"okay, but where's that in the actual pitch?\""
        },
        {
          "type": "paragraph",
          "text": "Your bio should act like a quiet footnote to the **query letter**:"
        },
        {
          "type": "list",
          "items": [
            "If your query promises humor with teeth, the bio should have a similar tonal logic.",
            "If your query is about obsession, the bio should show you obsess over something specific.",
            "If your query highlights a unique worldview, the bio shouldn't be a generic values statement."
          ]
        },
        {
          "type": "paragraph",
          "text": "So when you're editing, treat the bio and **query letter** like they're working together: complementing each other rather than repeating the same information."
        },
        {
          "type": "paragraph",
          "text": "Also: don't obsess over polish. Your bio does not need to sound like a finished brand campaign. It needs to sound like the mind that wrote the book."
        },
        {
          "type": "paragraph",
          "text": "And because this cluster is about avoiding awkwardness: this is where the reframing helps. Write your bio like the agent is meeting you for five minutes\u2014then stepping into your manuscript with that understanding."
        },
        {
          "type": "paragraph",
          "text": "No performance. Just a sneak peek into your mind, your attention, your expectations."
        }
      ],
      "image": {
        "url": "https://ik.imagekit.io/8cxvcsdnz/wqh/sprint_06/day_079/how-to-write-an-author-bio-that-makes-a-literary-agent-keep-reading/blog/blog_section_image_distinct_details_lived_experience_blog_section_landscape_f5f45848fde5.gif?updatedAt=1782427091575",
        "alt": "Body \u2014 structural breakdown",
        "width": 113,
        "height": 200,
        "creator": "mashable",
        "creatorUrl": "https://giphy.com/gifs/mashable-xgr6rjHCf1zRDVwWwT",
        "provider": "giphy",
        "role": "section"
      }
    },
    {
      "section_id": "h2_lessons_takeaways",
      "heading": "Lessons / Takeaways",
      "heading_slug": "lessons-takeaways",
      "keyword_key": "h2_lessons_takeaways",
      "keywords": [],
      "blocks": [
        {
          "type": "list",
          "items": [
            "**Your author bio is the voice preview.** It should signal **writing voice** and tone, not just life facts.",
            "**What makes an author bio stand out is specificity.** Replace generic achievements and \"passion\" words with concrete attention and lived observation.",
            "**Humor is allowed; self-worship isn't.** Use perspective-based humor to **show personality in a query bio** without demanding applause.",
            "**Theme matching is mechanism matching.** Don't list topics\u2014describe the kind of moments and decisions your stories repeatedly return to.",
            "**Your bio and query letter should agree on what kind of book this is.** Same human, different paragraph."
          ]
        }
      ],
      "image": {
        "url": "https://ik.imagekit.io/8cxvcsdnz/wqh/sprint_06/day_079/how-to-write-an-author-bio-that-makes-a-literary-agent-keep-reading/blog/blog_section_image_lessons_takeaways_blog_section_landscape_cd714d492786.jpeg?updatedAt=1782427092324",
        "alt": "Lessons / Takeaways",
        "width": 4752,
        "height": 3168,
        "creator": "Pixabay",
        "creatorUrl": "https://www.pexels.com/@pixabay",
        "provider": "pexels",
        "role": "section"
      }
    },
    {
      "section_id": "h2_role_of_the_author_bio_in_a_query_letter_first_impression",
      "heading": "Examples of author bios for query letters",
      "heading_slug": "examples-of-author-bios-for-query-letters",
      "keyword_key": "h2_role_of_the_author_bio_in_a_query_letter_first_impression",
      "keywords": [
        "first taste",
        "reading speed",
        "credibility",
        "instant vibe",
        "less polish more truth",
        "connection",
        "voice",
        "hinge detail",
        "stop and notice",
        "match"
      ],
      "blocks": [
        {
          "type": "paragraph",
          "text": "The strongest **examples of author bios for query letters** share a common pattern: they anchor big ideas in specific behavior or perspective."
        },
        {
          "type": "paragraph",
          "text": "**Pattern 1 (lived experience + storytelling belief):** \"I worked in emergency medicine for eight years, watching people negotiate between what their bodies were doing and what they told themselves was true. My characters live in that negotiation.\""
        },
        {
          "type": "paragraph",
          "text": "**Pattern 2 (observation + tonal promise):** \"I'm obsessed with the moment right before someone admits they're lost. In my work, I linger there.\""
        },
        {
          "type": "paragraph",
          "text": "**Pattern 3 (conflict type + how you handle it as a writer):** \"My stories keep asking: what happens when you love someone and don't like them? I'm interested in the people who stay in that contradiction.\""
        },
        {
          "type": "paragraph",
          "text": "Each of these bios does the same job: it gives the agent a prediction about what the manuscript will deliver, without relying on resume-speak or self-congratulation."
        }
      ],
      "image": null
    }
  ],
  "closingImage": null,
  "alsoLike": [
    {
      "title": "Publishing credits in your query letter bio? 7 mistakes that waste space the agent will not read",
      "url": "https://writequeryhook.com/blog/publishing-credits-in-your-query-letter-bio-7-mistakes-that-waste-space-the"
    },
    {
      "title": "Common author bio mistakes that turn your About page into a r\u00e9sum\u00e9",
      "url": "https://writequeryhook.com/blog/common-author-bio-mistakes-that-turn-your-about-page-into-a-resume"
    },
    {
      "title": "Author bio mistakes that waste your best sentences (and how to fix them fast)",
      "url": "https://writequeryhook.com/blog/author-bio-mistakes-that-waste-your-best-sentences-and-how-to-fix-them-fast"
    },
    {
      "title": "5 tips for listing publishing credits in a query letter without wasting bio space",
      "url": "https://writequeryhook.com/blog/5-tips-for-listing-publishing-credits-in-a-query-letter-without-wasting-bio"
    }
  ],
  "alsoLikeAfterIndex": 2,
  "faq": [
    {
      "question": "Why does an author bio matter in a query?",
      "answer": "The author bio is the first taste an agent gets of who you are as a person. It helps them see your voice and the kind of stories you're likely to create."
    },
    {
      "question": "Should my bio be funny or serious?",
      "answer": "It doesn't matter which tone you choose, as long as it's authentic. The key is showing who you are through your personality and perspective\u2014without turning it into a sales stunt."
    },
    {
      "question": "What makes a bio \"stand out\" to an agent?",
      "answer": "A standout bio includes distinctive, specific details that connect to your themes or storytelling style. The strongest examples of author bios for query letters show humor and authenticity grounded in lived experiences, so the agent can predict what the reader will get."
    },
    {
      "question": "How do I hype myself up without sounding fake?",
      "answer": "Write your bio as a sneak peek into the person the agent is about to meet. Treat it like a glimpse into your brain behind the book\u2014not a speech, not a performance."
    },
    {
      "question": "How can I connect my bio to my writing?",
      "answer": "Use your author bio to signal themes and tone you write with. When your interests, beliefs, and attention patterns reflect your manuscript, it becomes easier for a literary agent to understand your writing voice."
    }
  ],
  "closingBlocks": [
    {
      "type": "paragraph",
      "text": "Open your draft **author bio** right now and look for anything that could belong to a dozen other writers. Delete it. Then write three sentences that only fit you: what you notice, what you've lived, and what kind of story you keep failing to stop writing."
    },
    {
      "type": "paragraph",
      "text": "That's the bio that helps a **literary agent** keep reading\u2014because it finally sounds like the book you're actually trying to publish."
    }
  ],
  "relatedLinks": [
    {
      "title": "Publishing credits in your query letter bio? 7 mistakes that waste space the agent will not read",
      "url": "https://writequeryhook.com/blog/publishing-credits-in-your-query-letter-bio-7-mistakes-that-waste-space-the"
    }
  ]
} as const;
const SCHEMA_GRAPH = {
  "@graph": [
    {
      "@context": "https://schema.org",
      "@type": "Organization",
      "@id": "https://writequeryhook.com/#organization",
      "name": "Write Query Hook",
      "url": "https://writequeryhook.com",
      "logo": "https://writequeryhook.com/logo.png",
      "description": "WQH helps writers build query packages and navigate the submission process.",
      "sameAs": []
    },
    {
      "@context": "https://schema.org",
      "@type": "WebSite",
      "@id": "https://writequeryhook.com/#website",
      "url": "https://writequeryhook.com",
      "name": "Write Query Hook",
      "publisher": {
        "@id": "https://writequeryhook.com/#organization"
      },
      "inLanguage": "en-US"
    },
    {
      "@context": "https://schema.org",
      "@type": "BreadcrumbList",
      "@id": "https://writequeryhook.com/blog/how-to-write-an-author-bio-that-makes-a-literary-agent-keep-reading#breadcrumb",
      "itemListElement": [
        {
          "@type": "ListItem",
          "position": 1,
          "name": "Home",
          "item": "https://writequeryhook.com"
        },
        {
          "@type": "ListItem",
          "position": 2,
          "name": "Blog",
          "item": "https://writequeryhook.com/blog"
        },
        {
          "@type": "ListItem",
          "position": 3,
          "name": "How to write an author bio that makes a literary agent keep reading",
          "item": "https://writequeryhook.com/blog/how-to-write-an-author-bio-that-makes-a-literary-agent-keep-reading"
        }
      ]
    },
    {
      "@context": "https://schema.org",
      "@type": "WebPage",
      "@id": "https://writequeryhook.com/blog/how-to-write-an-author-bio-that-makes-a-literary-agent-keep-reading#webpage",
      "url": "https://writequeryhook.com/blog/how-to-write-an-author-bio-that-makes-a-literary-agent-keep-reading",
      "name": "How to write an author bio that makes a literary agent keep reading",
      "isPartOf": {
        "@id": "https://writequeryhook.com/#website"
      },
      "inLanguage": "en-US",
      "primaryImageOfPage": {
        "@id": "https://writequeryhook.com/blog/how-to-write-an-author-bio-that-makes-a-literary-agent-keep-reading#primaryimage"
      },
      "breadcrumb": {
        "@id": "https://writequeryhook.com/blog/how-to-write-an-author-bio-that-makes-a-literary-agent-keep-reading#breadcrumb"
      },
      "speakable": {
        "@type": "SpeakableSpecification",
        "cssSelector": [
          "h1",
          "h2",
          ".tldr-section",
          ".summary-section",
          "blockquote"
        ]
      }
    },
    {
      "@context": "https://schema.org",
      "@type": "BlogPosting",
      "@id": "https://writequeryhook.com/blog/how-to-write-an-author-bio-that-makes-a-literary-agent-keep-reading#article",
      "isPartOf": {
        "@id": "https://writequeryhook.com/blog/how-to-write-an-author-bio-that-makes-a-literary-agent-keep-reading#webpage"
      },
      "mainEntityOfPage": "https://writequeryhook.com/blog/how-to-write-an-author-bio-that-makes-a-literary-agent-keep-reading",
      "headline": "How to write an author bio that makes a literary agent keep reading",
      "alternativeHeadline": "How to write an author bio that makes a literary agent keep reading",
      "description": "A lot of writers treat the author bio like a formality: \"Here's my name. Here are my accomplishments. Anyway, here's the book.\"",
      "wordCount": 2535,
      "timeRequired": "PT13M",
      "articleSection": "Querying",
      "keywords": [
        "author bios",
        "submissions",
        "craft",
        "agents",
        "agent attention",
        "quick snapshot",
        "honesty",
        "specifics",
        "awkward self-promotion",
        "voice signal",
        "sneak peek",
        "match"
      ],
      "inLanguage": "en-US",
      "author": {
        "@id": "https://writequeryhook.com/#organization"
      },
      "publisher": {
        "@id": "https://writequeryhook.com/#organization"
      },
      "isAccessibleForFree": true,
      "image": {
        "@id": "https://writequeryhook.com/blog/how-to-write-an-author-bio-that-makes-a-literary-agent-keep-reading#primaryimage"
      },
      "mentions": [
        {
          "@type": "WebPage",
          "name": "Publishing credits in your query letter bio? 7 mistakes that waste space the agent will not read",
          "url": "https://writequeryhook.com/blog/publishing-credits-in-your-query-letter-bio-7-mistakes-that-waste-space-the"
        },
        {
          "@type": "WebPage",
          "name": "Common author bio mistakes that turn your About page into a r\u00e9sum\u00e9",
          "url": "https://writequeryhook.com/blog/common-author-bio-mistakes-that-turn-your-about-page-into-a-resume"
        },
        {
          "@type": "WebPage",
          "name": "Author bio mistakes that waste your best sentences (and how to fix them fast)",
          "url": "https://writequeryhook.com/blog/author-bio-mistakes-that-waste-your-best-sentences-and-how-to-fix-them-fast"
        },
        {
          "@type": "WebPage",
          "name": "5 tips for listing publishing credits in a query letter without wasting bio space",
          "url": "https://writequeryhook.com/blog/5-tips-for-listing-publishing-credits-in-a-query-letter-without-wasting-bio"
        }
      ]
    },
    {
      "@type": "ImageObject",
      "@id": "https://writequeryhook.com/blog/how-to-write-an-author-bio-that-makes-a-literary-agent-keep-reading#primaryimage",
      "url": "https://ik.imagekit.io/8cxvcsdnz/wqh/sprint_06/day_079/how-to-write-an-author-bio-that-makes-a-literary-agent-keep-reading/blog/blog_hero_query_anxiety_tiny_bio_blog_hero_landscape_653a672f0f3e.jpeg?updatedAt=1782427090361",
      "width": 3736,
      "height": 2393,
      "caption": "blog hero \u00b7 query anxiety tiny bio",
      "creditText": "Aykut \u00d6zen",
      "author": {
        "@type": "Person",
        "name": "Aykut \u00d6zen",
        "url": "https://www.pexels.com/@aykut-ozen-2159946844"
      },
      "@context": "https://schema.org"
    },
    {
      "@context": "https://schema.org",
      "@type": "FAQPage",
      "@id": "https://writequeryhook.com/blog/how-to-write-an-author-bio-that-makes-a-literary-agent-keep-reading#faq",
      "mainEntity": [
        {
          "@type": "Question",
          "name": "Why does an author bio matter in a query?",
          "acceptedAnswer": {
            "@type": "Answer",
            "text": "The author bio is the first taste an agent gets of who you are as a person. It helps them see your voice and the kind of stories you're likely to create."
          }
        },
        {
          "@type": "Question",
          "name": "Should my bio be funny or serious?",
          "acceptedAnswer": {
            "@type": "Answer",
            "text": "It doesn't matter which tone you choose, as long as it's authentic. The key is showing who you are through your personality and perspective\u2014without turning it into a sales stunt."
          }
        },
        {
          "@type": "Question",
          "name": "What makes a bio \"stand out\" to an agent?",
          "acceptedAnswer": {
            "@type": "Answer",
            "text": "A standout bio includes distinctive, specific details that connect to your themes or storytelling style. The strongest examples of author bios for query letters show humor and authenticity grounded in lived experiences, so the agent can predict what the reader will get."
          }
        },
        {
          "@type": "Question",
          "name": "How do I hype myself up without sounding fake?",
          "acceptedAnswer": {
            "@type": "Answer",
            "text": "Write your bio as a sneak peek into the person the agent is about to meet. Treat it like a glimpse into your brain behind the book\u2014not a speech, not a performance."
          }
        },
        {
          "@type": "Question",
          "name": "How can I connect my bio to my writing?",
          "acceptedAnswer": {
            "@type": "Answer",
            "text": "Use your author bio to signal themes and tone you write with. When your interests, beliefs, and attention patterns reflect your manuscript, it becomes easier for a literary agent to understand your writing voice."
          }
        }
      ]
    }
  ]
} as const;

export const metadata: Metadata = {
  title: PAGE_DATA.title,
  description: PAGE_DATA.description,
  keywords: PAGE_DATA.keywords as unknown as string[],
  alternates: { canonical: PAGE_DATA.canonicalUrl },
  openGraph: {
    title: PAGE_DATA.title,
    description: PAGE_DATA.description,
    url: PAGE_DATA.canonicalUrl,
    type: 'article',
    siteName: PAGE_DATA.siteName,
    locale: PAGE_DATA.locale,
    publishedTime: PAGE_DATA.publishedDate || undefined,
    modifiedTime: PAGE_DATA.modifiedDate || undefined,
    authors: PAGE_DATA.author?.name ? [PAGE_DATA.author.name] : undefined,
    section: PAGE_DATA.articleSection,
    images: PAGE_DATA.hero?.url
      ? [{ url: PAGE_DATA.hero.url, width: PAGE_DATA.hero.width, height: PAGE_DATA.hero.height, alt: PAGE_DATA.hero.alt }]
      : [],
  },
  twitter: {
    card: 'summary_large_image',
    title: PAGE_DATA.title,
    description: PAGE_DATA.description,
    images: PAGE_DATA.hero?.url ? [PAGE_DATA.hero.url] : [],
  },
};

// Render inline markdown ([links](/url), **bold**, *italic*) to real React nodes.
function renderInline(text: string, keyPrefix: string): any[] {
  const nodes: any[] = [];
  const pattern = /\[([^\]]+)\]\(([^)]+)\)|\*\*([^*]+)\*\*|(?<!\*)\*(?!\*)([^*]+)\*(?!\*)/g;
  let lastIndex = 0;
  let match: RegExpExecArray | null;
  let i = 0;
  while ((match = pattern.exec(text)) !== null) {
    if (match.index > lastIndex) {
      nodes.push(text.slice(lastIndex, match.index));
    }
    const key = `${keyPrefix}-i${i++}`;
    if (match[1] !== undefined) {
      const label = match[1];
      const href = match[2];
      if (href.startsWith('/')) {
        nodes.push(
          <Link key={key} href={href} className="font-medium text-[#1B4A56] underline underline-offset-2 hover:opacity-80">
            {label}
          </Link>,
        );
      } else {
        nodes.push(
          <a key={key} href={href} target="_blank" rel="noopener noreferrer"
             className="font-medium text-[#1B4A56] underline underline-offset-2 hover:opacity-80">
            {label}
          </a>,
        );
      }
    } else if (match[3] !== undefined) {
      nodes.push(<strong key={key} className="font-semibold">{match[3]}</strong>);
    } else if (match[4] !== undefined) {
      nodes.push(<em key={key}>{match[4]}</em>);
    }
    lastIndex = pattern.lastIndex;
  }
  if (lastIndex < text.length) {
    nodes.push(text.slice(lastIndex));
  }
  return nodes;
}

function renderBlock(block: any, key: string) {
  if (block.type === 'paragraph') {
    return <p key={key} className="mb-4 leading-7 text-[#1B4A56]">{renderInline(block.text, key)}</p>;
  }
  if (block.type === 'list') {
    return (
      <ul key={key} className="mb-4 list-disc pl-6 text-[#1B4A56]">
        {block.items.map((item: string, index: number) => (
          <li key={`${key}-${index}`} className="mb-2">{renderInline(item, `${key}-${index}`)}</li>
        ))}
      </ul>
    );
  }
  if (block.type === 'blockquote') {
    return (
      <blockquote key={key} className="mb-4 border-l-4 border-[#1B4A56] pl-4 italic text-[#1B4A56]">
        {renderInline(block.text, key)}
      </blockquote>
    );
  }
  if (block.type === 'subheading') {
    return <h3 key={key} className="mb-3 mt-6 text-xl font-semibold text-[#1B4A56]">{renderInline(block.text, key)}</h3>;
  }
  return null;
}

// Article column is max-w-3xl (~768px); images render full-width within it.
const FIGURE_SIZES = '(max-width: 768px) 100vw, 768px';

function Figure({ image }: { image: any }) {
  if (!image?.url) return null;
  const isHero = image.role === 'hero';
  // Render the STRAIGHT ImageKit URL via a plain <img> for every image (photos
  // and gifs). No next/image proxy/optimization: the raw candidate asset is
  // served as-is, and animated gifs keep animating.
  return (
    <figure className="mb-6">
      {(
        <img
          src={image.url}
          alt={image.alt || ''}
          loading={isHero ? 'eager' : 'lazy'}
          decoding="async"
          className="w-full rounded-xl object-cover"
        />
      )}
      {image.creator ? (
        <figcaption className="mt-2 text-xs text-[#1B4A56]/70">
          Photo:{' '}
          {image.creatorUrl ? (
            <a href={image.creatorUrl} target="_blank" rel="noopener noreferrer" className="underline">{image.creator}</a>
          ) : (
            image.creator
          )}
          {image.provider ? ` / ${image.provider}` : ''}
        </figcaption>
      ) : null}
    </figure>
  );
}

export default function Page() {
  return (
    <main className="min-h-screen bg-[#FAF0E6] px-6 py-12">
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(SCHEMA_GRAPH) }} />
      <article className="mx-auto max-w-3xl rounded-2xl bg-[#F0F0EA] p-8 shadow-sm">
        <nav aria-label="Breadcrumb" className="mb-6 text-xs text-[#1B4A56]/70">
          <ol className="flex flex-wrap gap-1">
            {PAGE_DATA.breadcrumbs.map((crumb: any, index: number) => (
              <li key={`crumb-${index}`} className="flex gap-1">
                {index > 0 ? <span aria-hidden="true">/</span> : null}
                {index < PAGE_DATA.breadcrumbs.length - 1 ? (
                  <Link href={crumb.item} className="underline hover:opacity-80">{crumb.name}</Link>
                ) : (
                  <span aria-current="page">{crumb.name}</span>
                )}
              </li>
            ))}
          </ol>
        </nav>

        <header className="mb-8">
          <h1 className="mb-4 text-4xl font-semibold text-[#1B4A56]">{PAGE_DATA.title}</h1>
          <div className="flex flex-wrap gap-3 text-sm text-[#1B4A56]">
            {PAGE_DATA.publishedDate ? (
              <time dateTime={PAGE_DATA.publishedDate}>
                {new Date(PAGE_DATA.publishedDate).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}
              </time>
            ) : null}
            {PAGE_DATA.publishedDate ? <span>&bull;</span> : null}
            <span>{PAGE_DATA.readTime}</span>
            {PAGE_DATA.author?.name ? <span>&bull;</span> : null}
            {PAGE_DATA.author?.name ? <span>By {PAGE_DATA.author.name}</span> : null}
          </div>
        </header>

        {PAGE_DATA.tldrBlocks.length > 0 ? (
          <section className="tldr-section mb-10 rounded-xl border border-[#1B4A56]/20 bg-[#FAF0E6] p-5">
            <h2 className="mb-2 text-sm font-bold uppercase tracking-[0.15em] text-[#1B4A56]">TL;DR</h2>
            {PAGE_DATA.tldrBlocks.map((block: any, index: number) => renderBlock(block, `tldr-${index}`))}
          </section>
        ) : null}

        {PAGE_DATA.sections.length > 1 ? (
          <nav aria-label="Table of contents" className="mb-10 rounded-xl bg-[#FAF0E6] p-5">
            <h2 className="mb-2 text-sm font-bold uppercase tracking-[0.15em] text-[#1B4A56]">On this page</h2>
            <ul className="list-disc pl-5 text-[#1B4A56]">
              {PAGE_DATA.sections.map((section: any) => (
                <li key={`toc-${section.heading_slug}`} className="mb-1">
                  <a href={`#${section.heading_slug}`} className="underline underline-offset-2 hover:opacity-80">{section.heading}</a>
                </li>
              ))}
            </ul>
          </nav>
        ) : null}

        <section className="mb-10">
          <Figure image={PAGE_DATA.hero} />
          {PAGE_DATA.openingBlocks.map((block: any, index: number) => renderBlock(block, `opening-${index}`))}
        </section>

        {PAGE_DATA.sections.map((section: any, sIdx: number) => (
          <Fragment key={section.section_id}>
            <section className="mb-10">
              <h2 id={section.heading_slug} className="mb-4 scroll-mt-24 text-2xl font-semibold text-[#1B4A56]">{section.heading}</h2>
              <Figure image={section.image} />
              {section.blocks.map((block: any, index: number) => renderBlock(block, `${section.section_id}-${index}`))}
            </section>
            {PAGE_DATA.alsoLike.length > 0 && sIdx === PAGE_DATA.alsoLikeAfterIndex ? (
              <aside className="mb-10 rounded-xl border border-[#1B4A56]/20 bg-[#FAF0E6] p-5">
                <h2 className="mb-3 text-sm font-bold uppercase tracking-[0.15em] text-[#1B4A56]">You may also like</h2>
                <ul className="list-disc pl-6 text-[#1B4A56]">
                  {PAGE_DATA.alsoLike.map((link: any, index: number) => (
                    <li key={`alsolike-${index}`} className="mb-2">
                      <Link href={link.url.replace(PAGE_DATA.siteUrl, '')} className="underline underline-offset-2 hover:opacity-80">
                        {link.title}
                      </Link>
                    </li>
                  ))}
                </ul>
              </aside>
            ) : null}
          </Fragment>
        ))}

        {PAGE_DATA.faq.length > 0 ? (
          <section className="mb-10">
            <h2 className="mb-4 text-2xl font-semibold text-[#1B4A56]">Frequently asked questions</h2>
            {PAGE_DATA.faq.map((item: any, index: number) => (
              <div key={`faq-${index}`} className="mb-5">
                <h3 className="mb-2 text-lg font-semibold text-[#1B4A56]">{item.question}</h3>
                <p className="leading-7 text-[#1B4A56]">{renderInline(item.answer, `faq-a-${index}`)}</p>
              </div>
            ))}
          </section>
        ) : null}

        <section className="mb-10">
          <h2 className="mb-4 text-2xl font-semibold text-[#1B4A56]">The bottom line</h2>
          <Figure image={PAGE_DATA.closingImage} />
          {PAGE_DATA.closingBlocks.map((block: any, index: number) => renderBlock(block, `closing-${index}`))}
        </section>

        {PAGE_DATA.relatedLinks.length > 0 ? (
          <section className="border-t border-[#1B4A56]/20 pt-6">
            <h2 className="mb-4 text-2xl font-semibold text-[#1B4A56]">Continue reading</h2>
            <ul className="list-disc pl-6 text-[#1B4A56]">
              {PAGE_DATA.relatedLinks.map((link: any, index: number) => (
                <li key={`related-${index}`} className="mb-2">
                  <Link href={link.url.replace(PAGE_DATA.siteUrl, '')} className="underline underline-offset-2 hover:opacity-80">
                    {link.title}
                  </Link>
                </li>
              ))}
            </ul>
          </section>
        ) : null}
      </article>
    </main>
  );
}
